### ISSUE TITLE
CI Paused Until November 24th, 2023

### ISSUE THREAD

**Issue by eeeebbbbrrrr** [pgcentralfoundation/pgrx#1398]
We blew our CI budget already this month, so CI is paused until the next billing cycle... November 24th, 2023.  Enjoy a week off over the US Thanksgiving holiday!

Also, now would be a good time to contact the pgcentral foundation about joining!

**Comment by orf** [comment]
Out of interest, can you mention why standard (and free) github runners not suitable and what requires us to use custom ones?

**Comment by eeeebbbbrrrr** [comment]
It boils down to performance and disk usage. The free runners don’t have enough cores to finish our CI jobs in a reasonable time (they already take around 30 minutes per) and the free runners don’t have enough storage space to handle the intermediate artifacts. 

We’ve spent countless hours getting the jobs to a tolerable level and it’s now cheaper to throw money at it.

**Comment by workingjubilee** [comment]
@orf The default runners have sufficiently small disk space that they require hacks like clearing the entire target directory midway to clean out intermediates in order to complete our CI test run. Failure to do so, if we are generating sufficient intermediates, does not fail gracefully: it falls over wailing pathetically on whatever test put it over the disk limit. And it does not explain what happened. It just is a series of bizarre and opaque errors.

As we have, in general, _insufficient_ testing, having a situation where, randomly, we are punished for adding tests, is not acceptable.

**Comment by workingjubilee** [comment]
Now and then we spot an optimization that reduces our disk usage, and of course we take it:
- https://github.com/pgcentralfoundation/pgrx/pull/1249
- https://github.com/pgcentralfoundation/pgrx/pull/1316

...but these often don't significantly help the people using pgrx to build software that does stuff. Of course, if someone put quite a lot of time in, they could improve it, and a few of those would translate a little. Then we could, in a situation like this, endure slower iteration cycles rather than simply shrugging and deferring running CI for a week. But if I had to wait the almost-hour the pgrx CI used to take, for every iteration, I would simply not have bothered to solve certain problems, like e.g.
- https://github.com/pgcentralfoundation/pgrx/pull/1325
