### ISSUE TITLE
General how-to for adding support to a custom version of Postgres

### ISSUE THREAD

**Issue by tumluliu** [pgcentralfoundation/pgrx#1477]
For some reason, my friends and I will have to support an ancient PG version 9.2. I would not expect it will be officially supported by `pgrx` as that's unnecessary. So we are trying to figure out how to do that by ourselves. Some progress has been made so far:

- it's possible to have `pg9` included from `pgrx init`, `pgrx status`, `pgrx start/stop` and `pgrx connect`
- `package` and `install` are not yet working, and I'm planning to make some changes from the `pgrx-pg-sys` sub-dir

Before adding the `include/pg9.h`, `src/include/pg9.rs` and `src/include/pg12_oids.rs`, I would like to ask if these files really supposed to be added manually, or should be generated somehow? tbh, they look like machine-generated files. Could you shed some lights here by providing some high-level steps? That would be super appreciated. I'm sorry for such a weird requirement.

**Comment by workingjubilee** [comment]
> Before adding the include/pg9.h, src/include/pg9.rs and src/include/pg12_oids.rs, I would like to ask if these files really supposed to be added manually, or should be generated somehow? tbh, they look like machine-generated files. Could you shed some lights here by providing some high-level steps? That would be super appreciated. I'm sorry for such a weird requirement.

The `src/include/*.rs` files are machine-generated, the `include/*.h` are hand-written to accommodate version differences (code gets moved around, and such). The `.rs` files are only checked-in for documentation purposes: the versions you see in the repo are never actually used, but rather it's built anew from your Postgres, so that it remains accurate for the latest minor versions, even if we don't update.

I am happy to add _some_ support for naming "officially unsupported" versions in a more **general** way, because that's what is necessary every time we add a new version, especially release candidates. But you have to understand that pgrx is going to be linking against certain symbols that might not even exist in these versions, and that's just going to be hopeless.

**Comment by workingjubilee** [comment]
An example from the codebase:
https://github.com/pgcentralfoundation/pgrx/blob/a5625169297cd378c3d206cbf501025b5b2f6ba8/pgrx/src/fcinfo.rs#L334-L338

This cast occurs because `*mut T::cast<U>` is defined by the pointee type, and we chose to write it with the turbofish. We could have written it by instead writing
```rust
let fcinfo_ptr: pg_sys::FunctionCallInfo = { /* expr */ };
```

That way the `U` of `.cast()` would be inferred. But that struct was renamed between versions! Even if we fixed that to be slightly more idiomatic (for Postgres idioms, not Rust), there is the other problem of needing to know the size:
```rust
     std::mem::size_of::<pg_sys::FunctionCallInfoBaseData>() 
```
This is because we can't simply use the Postgres macros, as function macros do not get translated by bindgen. And, for instance, `NullableDatum` doesn't even exist in pg9! So in order to really make this work, you'd have to add support for injecting new code in this "name a custom version" mode, so that you could add sufficient version-dependent shims to make this work.

**Comment by tumluliu** [comment]
@workingjubilee Thanks very much for your kind help. I think I will start then from adding the `include/pg9.h` firstly, and then play with some dirty hacks locally. Will get back to here if I could not proceed anymore. Thanks again!

**Comment by tumluliu** [comment]
Hey @workingjubilee, it seems that I could successfully build `pgrx-pg-sys` after doing the following steps:

- add `pg9` into the `SUPPORTED_VERSIONS()`, i.e. a new vec item `PgVersion::new(9, PgMinorVersion::Release(2), Some(Url::parse("https://ftp.postgresql.org/pub/source/v9.2.4/postgresql-9.2.4.tar.bz2").unwrap())),` from the `Vec<PgVersion` list
- manually add `include/pg9.h` (with [pg10.h](https://github.com/pgcentralfoundation/pgrx/blob/daa0ecf321ce65c68f23c53a6dd6b420098171cb/pgx-pg-sys/include/pg10.h) and the real pg9 header files list as references)
- add `pg9 = [ "pgrx-pg-sys/pg9" ]` into `pgrx/Cargo.toml`
- add `pg9 = [ ]` into `pgrx-pg-sys/Cargo.toml`
- make a slight change from `cschim/pgrx-cshim.c` with:

```
#define IS_PG_9 (PG_VERSION_NUM >= 90000 && PG_VERSION_NUM < 100000)
#if IS_PG_9 == 0
    #include "nodes/pathnodes.h"
#else
    #include "optimizer/pathnode.h"
#endif
```

Then run `cargo build` under the proj root, and it succeeded. After that, I can see the generated `src/include/pg9.rs` and `src/include/pg9_oids.rs`. Then I tried running an example (after re-installing `cargo-pgrx` and running `cargo pgrx init`), but it failed with:

```
❯ cargo pgrx run pg9 --pgcli
       Using CliArgument("pg9") and `pg_config` from /home/xx/.pgrx/9.2/pgrx-install/bin/pg_config
    Building extension with features pg9
     Running command "/home/xx/.rustup/toolchains/nightly-2023-09-01-x86_64-unknown-linux-gnu/bin/cargo" "build" "--features" "pg9" "--no-default-features" "--message-format=json-render-diagnostics"
error: none of the selected packages contains these features: pg9, did you mean: pg11, pg12, pg13, pg14, pg15?
```

I guess I'm closer to the goal, but could not figure out why it complained with the unrecognized `pg9` here. My gut feeling is that I forget to add `pg9` into some `features` section of some `Cargo.toml` file, but not sure. Could you provide me some further hints here? Thanks!

**Comment by tumluliu** [comment]
ok, I found the reason that I forget to update the `Cargo.toml` from the example project. Sorry for disturbing. After changing the `pgrx` dep location to the local version and adding `pg9` there, the real error storm came.. Will try to fix them.

**Comment by tumluliu** [comment]
have fixed 200+ compiling errors from `pgrx-pg-sys`, then saw another 240+ complaints from `pgrx`. Now it's been reduced to ~170, but feel more and more hopeless...

**Comment by eeeebbbbrrrr** [comment]
> For some reason, my friends and I will have to support an ancient PG version 9.2.

Was this your idea or theirs?  Somebody might need a new friend group. ;)

There are drastic and significant Postgres code changes that happened after 9.6, which is, in part, what led them to jump directly to 10. 

I am dubious that enough of pgrx will be backwards compatible that far. 

What’s your end game here?  Have you considered other approaches that don’t involve pgrx?

**Comment by eeeebbbbrrrr** [comment]
Also, I'd like to point out that you shouldn't be supporting any "v9", you should be supporting a specific v9 point release.  Up top you said v9.2, so that's what you should do.

Prior to v10, a point release jump, say from v9.1 to v9.2, was actually a "major" change.

**Comment by workingjubilee** [comment]
> have fixed 200+ compiling errors from `pgrx-pg-sys`, then saw another 240+ complaints from `pgrx`. Now it's been reduced to ~170, but feel more and more hopeless...

Hello, my apologies. I was unable to access the internet while my power was out.

I am honestly not surprised that it takes so much work. Most of those are probably adding `"pg9"` to appearances of various `cfg(any(feature = "pg12", feature = "pg13", ..))` features. Part of the reason I am happy to make pgrx _slightly_ more version agnostic is that while you have quite a lot of work for you if you continue down this road, there is a lot of fussy and tedious work to do to get any new version over the line, which adds noise in insignificant cases, which makes it harder to verify if something important for soundness changed (or didn't).

I agree with Eric that supporting `pg9dot2` is going to be abominable for you, though I will note that because the tooling in spots encodes assumptions like "a Postgres major version feature is written `pg{number}`", you probably would need to write down `"pg9"` anyways. That's just another assumption that was perfectly viable with a minimum support boundary of Postgres 10 and only supporting each Postgres major.

I suggest using `#[cfg(not(feature = "pg9"))]` on _every_ module you have not confirmed you yet require. You will have to have `pg_sys` and `fcinfo` to use `#[pg_extern]`, and I believe `#[pg_guard]` also requires `pg_sys`.

Note that explaining all this, and these "suggestions", does not mean I endorse using pgrx with Postgres v9.2 for the reasons already stated. Rather, I have sympathy with people give implausible and daunting tasks. I skipped asking whether this was a good idea because the answer was obviously "No", so there must be _some_ good reason to do this with such an old and incredibly unsupported Postgres version. I can only imagine it may have something to do with the fact that, as I understand it, very old versions of Postgres had less support for logical replication than they do now? But they did have streaming binary replication as-of 9.0, though I don't know if 9.2 was still missing some essential feature for that? That may imply more downtime for DB migration and upgrades in the best cases.

...so this work _might_ make sense for somehow hacking in whatever is missing. I would hope the purpose of this is ultimately so you can move off a version that was end-of-life 6 years ago!

**Comment by tumluliu** [comment]
> > For some reason, my friends and I will have to support an ancient PG version 9.2.
> 
> Was this your idea or theirs? Somebody might need a new friend group. ;)
> 
> There are drastic and significant Postgres code changes that happened after 9.6, which is, in part, what led them to jump directly to 10.
> 
> I am dubious that enough of pgrx will be backwards compatible that far.
> 
> What’s your end game here? Have you considered other approaches that don’t involve pgrx?

Haha, thanks for your suggestion. Actually none of us are very motivated to do this. I can disclose a bit more background, that is we are asked to try supporting Postgres-XL 9.2 - yes the clustered version PG. Then we started this PoC adventure. I didn't mention that before as I don't want to introduce another complexity dimension to you, but only focus on v9.2 atm. 

As of now, I'm still trying to fix the errors from `pgrx`, but very very slow as that requires quite some learning and understanding of those low-level details. I'm not very optimistic that we could make it successfully tbh.

**Comment by tumluliu** [comment]
> > have fixed 200+ compiling errors from `pgrx-pg-sys`, then saw another 240+ complaints from `pgrx`. Now it's been reduced to ~170, but feel more and more hopeless...
> 
> Hello, my apologies. I was unable to access the internet while my power was out.
> 
> I am honestly not surprised that it takes so much work. Most of those are probably adding `"pg9"` to appearances of various `cfg(any(feature = "pg12", feature = "pg13", ..))` features. Part of the reason I am happy to make pgrx _slightly_ more version agnostic is that while you have quite a lot of work for you if you continue down this road, there is a lot of fussy and tedious work to do to get any new version over the line, which adds noise in insignificant cases, which makes it harder to verify if something important for soundness changed (or didn't).
> 
> I agree with Eric that supporting `pg9dot2` is going to be abominable for you, though I will note that because the tooling in spots encodes assumptions like "a Postgres major version feature is written `pg{number}`", you probably would need to write down `"pg9"` anyways. That's just another assumption that was perfectly viable with a minimum support boundary of Postgres 10 and only supporting each Postgres major.
> 
> I suggest using `#[cfg(not(feature = "pg9"))]` on _every_ module you have not confirmed you yet require. You will have to have `pg_sys` and `fcinfo` to use `#[pg_extern]`, and I believe `#[pg_guard]` also requires `pg_sys`.
> 
> Note that explaining all this, and these "suggestions", does not mean I endorse using pgrx with Postgres v9.2 for the reasons already stated. Rather, I have sympathy with people give implausible and daunting tasks. I skipped asking whether this was a good idea because the answer was obviously "No", so there must be _some_ good reason to do this with such an old and incredibly unsupported Postgres version. I can only imagine it may have something to do with the fact that, as I understand it, very old versions of Postgres had less support for logical replication than they do now? But they did have streaming binary replication as-of 9.0, though I don't know if 9.2 was still missing some essential feature for that? That may imply more downtime for DB migration and upgrades in the best cases.
> 
> ...so this work _might_ make sense for somehow hacking in whatever is missing. I would hope the purpose of this is ultimately so you can move off a version that was end-of-life 6 years ago!

@workingjubilee thanks very very much for your professional insights, suggestions and kind sympathy. As I mentioned in the above reply to eeeebbbbrrrr, one major reason of supporting 9.2 is relevant to postgres-xl. But anyway, we will continue to try for another couple of days. If it's not really applicable, we probably will either 1). fall back to some other ancient repo like `postgres-extension.rs`, or 2). have to write the extension in `C` but call other rust crates via their c bindings. Option 2 is more likely the way to go, although it's also not very ideal to me.

So I think it's time to close this ticket. Once again, thanks very much for your timely, professional and patient supports.

**Comment by workingjubilee** [comment]
Ah, I see!

Interesting. It seems the [Postgres XL source downloads](https://www.postgres-xl.org/download/) include a Postgres XL 9.5 stable release and a Postgres XL 10-R1.1 release, and they suggestively indicate their development is "10-compatible". Tragic. If Postgres 10 was in use, then there would not be so many questions: pgrx has definitely supported that before, although it would still be a haul to re-add that support.
