### ISSUE TITLE
Error: Unable to find `pg_config` on the system $PATH

### ISSUE THREAD

**Issue by bpsbits-org** [pgcentralfoundation/pgrx#1551]
Trying to build package:

```shell
cargo pgrx package
```

Getting an error:

```
Unable to find `pg_config` on the system $PATH
```

But 

```shell
cargo pgrx run
```

works fine. No issues.

```
Using DefaultFeature("pg16") and `pg_config` from /home/developer/.pgrx/16.2/pgrx-install/bin/pg_config
Building extension with features pg16
```

What I'm missing?

Even searching for ideas on Google turned up nothing.

**Comment by eeeebbbbrrrr** [comment]
https://github.com/pgcentralfoundation/pgrx/tree/develop/cargo-pgrx#building-an-installation-package

If you have further questions about it, feel free to reopen this issue.

**Comment by kzhui125** [comment]
I am new to pgrx, and also confused with the docs. After searched a lot, then I know that pg_config is binary.

so `cargo pgrx package --pg-config /opt/homebrew/Cellar/postgresql@16/16.2_1/bin/pg_config`
and `cargo pgrx package --pg-config /Users/xx/.pgrx/16.2/pgrx-install/bin/pg_config` works

this is not friendly to new users, since `cargo pgrx run pg16` works, `cargo pgrx package pg16`  should work like `run`
