### ISSUE TITLE
Pass 64-bit types by reference on 32-bit platforms

### ISSUE THREAD

**Issue by CoderPuppy** [pgcentralfoundation/pgrx#1685]
Int64, UInt64 and Float8 are all passed by reference when the pointer size is less than 64 bit. In Postgres this is controlled by the `USE_FLOAT8_BYVAL` macro defined in [pg_config_manual.h](https://git.postgresql.org/gitweb/?p=postgresql.git;a=blob;f=src/include/pg_config_manual.h;h=f941ee2faf86b84a9d76b74269bec88d421fcbb7;hb=HEAD#l76), which is used when defining `DatumGetInt64`/`UIn64`/`Float8` and `Int64`/`UInt64`/`Float8GetDatum` in [postgres.h](https://git.postgresql.org/gitweb/?p=postgresql.git;a=blob;f=src/include/postgres.h;h=5d5fd7813e8086ae5ec148c9ba391b1ee836d040;hb=HEAD#l378) (and propagated to `FLOAT8PASSBYVAL`). The same logic should be implemented in `IntoDatum` and `FromDatum` for `i64`, `u64` and `f64`.

**Comment by workingjubilee** [comment]
It is documented in the [system requirements](https://github.com/pgcentralfoundation/pgrx?tab=readme-ov-file#system-requirements) that we do not support 32-bit systems.

While it mentions some examples, these are not the only cases that assume a 64-bit Datum type. Making pgrx work on 32-bit very well requires more than these changes, and it requires pervasive changes, because we e.g. provide a `pg_sys::Datum::from(i64)`. That cannot work except by truncating data on a 32-bit system.

While we have merged changes that make it a little easier to run pgrx on a 32-bit system before, this is the point where things become more than incidentally adding support. I really want to know why we'd be adding support. Finishing 32-bit support is going to cost hundreds of lines of code of revision and review.

And I'd want real tests, here, that I can run **while on a 64-bit system**, because otherwise I'm going to break it again. With a test suite that is a command away, I at least can lean on those.

**Comment by workingjubilee** [comment]
Right, so, I'm sorry but we can't go to the considerable effort of supporting this (and it requires much more pervasive changes than just #1686 offered) without tests and considerable investment *back*. Closing this because this will never transpire unless someone is willing to walk the entire walk... I would expect it to take months, plural, to hammer down all the bugs, because it's not just a small change here and there.

**Comment by eeeebbbbrrrr** [comment]
co-signed
