### ISSUE TITLE
Upgrading to 0.12.4

### ISSUE THREAD

**Issue by jawj** [pgcentralfoundation/pgrx#1888]
Based on the README I think it's is on the immediate roadmap to make this unnecessary. But in the meantime, here's a brief note for anyone having trouble with upgrading from 0.11 to 0.12.

After running `cargo pgrx upgrade`, I was getting this error: 

```
error: no bin target named `pgrx_embed_myext`
```

It turned out I also needed to do the following:

* Create a file `src/bin/pgrx_embed.rs` containing only the line `::pgrx::pgrx_embed!();`.
* In `Cargo.toml`:
    * Under `[features]`, delete `pg11 = ["pgrx/pg11", "pgrx-tests/pg11" ]`
    * Also under `[features]`, add `pg17 = ["pgrx/pg17", "pgrx-tests/pg17" ]`
    * Under `[lib]`, Change `crate-type = ["cdylib"]` to `crate-type = ["cdylib", "lib"]`
    * Add a new section like the following, but replacing `myext` with the name of your extension:

```
[[bin]]
name = "pgrx_embed_myext"
path = "./src/bin/pgrx_embed.rs"
```

**Comment by montanalow** [comment]
Just leaving a note for others upgrading since this list helped me. It appears the initialization order from extension_sql! and extension_sql_file! seems to have changed from a default of finalize to bootstrap, so you may need to add the finalize keyword if your sql depends on things in the extension being executed first. e,g,

extension_sql_file!("../sql/schema.sql", name = "schema", finalize);
