### ISSUE TITLE
Offline installation cargo-pgx

### ISSUE THREAD

**Issue by nikhil-postgres** [pgcentralfoundation/pgrx#252]
Hello,

Is there a way to install cargo-pgx without using the command 'cargo install cargo-pgx'? This command required internet access. We want to test promscale_extension for which cargo-pgx is a dependency.

**Comment by nikhil-postgres** [comment]
Adding error when running cargo install cargo-pgx

```
cargo install  cargo-pgx
    Updating crates.io index

warning: spurious network error (2 tries remaining): failed to connect to github.com: Connection timed out; class=Os (2)
warning: spurious network error (1 tries remaining): failed to connect to github.com: Connection timed out; class=Os (2)
```

**Comment by yellapantula** [comment]
Hi was a solution reached for the above? I am trying to do the same install cargo-pgx without internet, and no luck

**Comment by yellapantula** [comment]
cargo install cargo-pgx
    Updating crates.io index
warning: spurious network error (2 tries remaining): [35] SSL connect error (error:1408F10B:SSL routines:ssl3_get_record:wrong version number); class=Net (12)
warning: spurious network error (1 tries remaining): [35] SSL connect error (error:1408F10B:SSL routines:ssl3_get_record:wrong version number); class=Net (12)


The box does not have internet connection

**Comment by workingjubilee** [comment]
You must build from source as mentioned,
```bash
cd /path/to/src/of/pgx
cargo install --path ./cargo-pgx
```

In addition, you can have better responses from cargo by just telling it to use `--offline`.

**Comment by yellapantula** [comment]
So I downloading the official cargo-pgx repo from github and installing from it. It's unable to find another package called 'atty' as it cannot connect to crates.io registry which is on the internet. 

cargo install  --offline --path /home/ay***/pgx-master/cargo-pgx
  Installing cargo-pgx v0.4.5 (/home/ay***/pgx-master/cargo-pgx)
error: failed to compile `cargo-pgx v0.4.5 (/home/ay***/pgx-master/cargo-pgx)`, intermediate artifacts can be found at `/home/ay***/pgx-master/target`

Caused by:
  no matching package named `atty` found
  location searched: registry `crates-io`
  required by package `cargo-pgx v0.4.5 (/home/ay***/pgx-master/cargo-pgx)`
  As a reminder, you're using offline mode (--offline) which can sometimes cause surprising resolution failures, if this error is too confusing you may wish to retry without the offline flag.

**Comment by Hoverbear** [comment]
Yup, you'll need to be online at least once to fetch the dependencies, or use the `cargo vendor` command on a computer that does have internet (https://doc.rust-lang.org/cargo/commands/cargo-vendor.html)
