### ISSUE TITLE
Obscure schema generator error for `pg_extern` function returning u32

### ISSUE THREAD

**Issue by EdMcBane** [pgcentralfoundation/pgrx#951]
Creating a `[pg_extern]` function that returns u32 compiles fine, but the schema generator reports a very obscure error:

```rust
#[pg_extern]
fn foobar() -> u32 {
    42
}
```

```
Error: 
   0: Could not write SQL to /Users/edmcbane/.pgx/13.9/pgx-install/share/postgresql/extension/rewind--0.0.0.sql
   1: Got non-plain mapped/composite return variant SQL in what macro-expansion thought was a type, got: One(Source { array_brackets: false })
```

**Comment by workingjubilee** [comment]
The argument form of this was also reported in https://github.com/pgcentralfoundation/pgrx/issues/1536 and the diagnostics have significantly improved, see https://github.com/pgcentralfoundation/pgrx/pull/1577

I still intend to improve this a bit, but this issue is a duplicate now, even though it came first.
